### ISSUE TITLE
Error resign

### ISSUE THREAD

**Issue by volram** [asdfjkl/jerry#2] opened 2015-07-13 02:57 UTC
![error jerry](https://cloud.githubusercontent.com/assets/13249913/8641851/ab10d04a-28f1-11e5-932d-7a0d27a62cbf.png)

**Comment by asdfjkl** [comment] 2015-07-14 22:19
That is indeed a little bit too early to resign :-) I will look into it. Thank you very much for reporting!

**Comment by asdfjkl** [comment] 2015-07-18 20:44
Note that this will not be fixed in the 1.0 branch, since I am trying hard to get a version 2.0 with various bug fixes and new features.

**Comment by asdfjkl** [comment] 2015-12-22 11:46
I cannot reproduce this in version 2.0. Please let me know if the error still exists. Closing this for now...

**Closed by asdfjkl** 2015-12-22 11:46 UTC
