### ISSUE TITLE
When I try to modify the set up of the pieces of the board by 'Enter Position' function the black Bishop image is not shown on the right panel

### ISSUE THREAD

**Issue by esocrates** [asdfjkl/jerry#27] opened 2016-11-08 15:54 UTC
Dear Team, 
When I try to modify the set up of the pieces of the board by 'Enter Position' function the black Bishop image is not shown on the right panel.
I am using jerry 3.0.5 version under Windows 7 Ultimate SP 1
This problem was not in the 3.0.4 version
Thanks for your great work
Regards
Enrique

**Comment by asdfjkl** [comment] 2016-11-13 12:30
... I cannot reproduce the problem on my machine. Do you have some more infos on your machine?
a) what path in Jerry installed in? Are there spaces in the directory name?
b) what piece images do you use? Is this independent on the used piece images, or e.g. the image does not show only for merida pieces?
c) is there an image in Jerry_Chess_Gui\res\pieces\merida\bb.svg?

Thanks for your support!

**Comment by esocrates** [comment] 2016-11-13 13:21
Description of the problem:

1- I try to set up a new position by 'E' and do it. Everything is OK

2- When I try to set up a new positon from the previous one by 'E' same pieces are not shown.

3- It happens only when Merida pieces

4- It was not happen using the 3.04 version

4- Windows 7 SP 1 [Spanish version]
5- Install Directory C:\Program Files\Jerry_Chess_GUI

**Comment by asdfjkl** [comment] 2016-11-13 20:36
... can reproduce this now. Will work on a fix. Thanks again!

**Comment by asdfjkl** [comment] 2016-11-18 19:30
fixed in 18c3f8867a45d7ec69f9402ab15b2f043ced6c99

Again thanks for spotting and reporting!

**Closed by asdfjkl** 2016-11-18 19:30 UTC
Labels: bug
